version: '2'

services:
#  app1:
#    image: 'galacticalex/com.alex.crud:latest'
#    build:
#      context: .
#    restart: always
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_IP}/firstDB
#      SPRING_DATASOURCE_USERNAME: ${PGUSERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${PGPASSWORD}
#    ports:
#      - "8080:8080"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: 50m

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PGUSERNAME}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: firstDB
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: 50m
