spring:
  #App settings
  application:
    name: crud
  #Hibernate settings
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

  #Datasource settings
  datasource:
    url: jdbc:postgresql://localhost:5432/firstDB
    username: ${PGUSERNAME}
    password: ${PGPASSWORD}
  #Server settings
server:
  servlet:
    context-path: /alex-app
  error:
    include-message: always

  #Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "health, metrics, info, heapdump"
