spring:
  #App settings
  application:
    name: crud
  #Hibernate settings
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

  #Datasource settings
  datasource:
    url: jdbc:postgresql://${DB_IP}/firstDB
    username: ${PGUSERNAME}
    password: ${PGPASSWORD}
  #Server settings
server:
  error:
    include-message: always
