# name: Build & Deploy

# on:
#   push:
#     branches: [ "master" ]

# jobs:

#   push_compose:
#     name: Push docker-compose.yaml to remote server
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Copy docker-compose.yaml via SSH
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.HOST_IP }}
#           username: ${{ secrets.SSH_USER }}
#           port: 22
#           key: ${{ secrets.SSH_KEY }}
#           source: "docker-compose.yml"
#           target: "/home/${{ secrets.SSH_USER }}/crud/"
#           overwrite: true
          
#   build_and_push:
#     runs-on: ubuntu-latest
#     needs: [push_compose]
#     steps:
#     - uses: actions/checkout@v3
#     - name: login to dockerhub
#       uses: docker/login-action@v3.1.0
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
#     - name: set up buildx
#       uses: docker/setup-buildx-action@v3.2.0
#       with:
#        version: v0.7.0
      
#     - name: Build and push Docker images
#       uses: docker/build-push-action@v5.3.0
#       with:
#         file: ./Dockerfile
#         push: true
#         tags: galacticalex/com.alex.crud
        
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    needs: [build_and_push, push_compose]
#    steps:
#      - name: Connect with SSH and Deploy
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.HOST_IP }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#
#            cd crud
#            docker-compose pull
#            docker-compose up -d
